include: 
    project: docker/template
    file: debian-pkg-ng.yaml

variables:
    package_name: "evok"
    build_for_architecture: "armhf arm64"
    build_for_distribution: "newstable"
    build_independent_for: "newstable"
    mirror_to_github: "yes"
    github_url: "git@github.com:UniPiTechnology/evok.git"
    devel_repository: private_patrik
